import React, { useState } from "react"; import ConfirmationModal from "../Common/ConfirmationModal";

const LoginRegister = () => { const [showRegister, setShowRegister] = useState(false); const [modal, setModal] = useState({ show: false, message: "" });

// Login handler const handleLogin = async (e) => { e.preventDefault(); const form = e.target; const data = new FormData(form); const res = await fetch("http://localhost:5000/login", { method: "POST", body: data, }); const result = await res.json(); if (result.success) { window.location.href = "/produtos"; } else { setModal({ show: true, message: result.message }); } };

// Register handler const handleRegister = async (e) => { e.preventDefault(); const form = e.target; const data = new FormData(form); const res = await fetch("http://localhost:5000/register", { method: "POST", body: data, }); const result = await res.json(); setModal({ show: true, message: result.message }); if (result.success) { setShowRegister(false); form.reset(); } };


return ( <div className="auth-container"> {!showRegister ? ( <div className="auth-box"> <h2>Login</h2> <form id="loginForm" onSubmit={handleLogin}> <div className="form-group"> <label htmlFor="username">Usuário:</label> <input type="text" id="username" name="username" required /> </div> <div className="form-group"> <label htmlFor="password">Senha:</label> <input type="password" id="password" name="password" required /> </div> <button type="submit">Entrar</button> </form> <button className="switch-btn" onClick={() => setShowRegister(true)}> Criar nova conta </button> </div> ) : ( <div className="auth-box"> <h2>Cadastro</h2> <form id="registerForm" onSubmit={handleRegister}> <div className="form-group"> <label htmlFor="reg-username">Usuário:</label> <input type="text" id="reg-username" name="username" required /> </div> <div className="form-group"> <label htmlFor="reg-password">Senha:</label> <input type="password" id="reg-password" name="password" required /> </div> <button type="submit">Cadastrar</button> </form> <button className="switch-btn" onClick={() => setShowRegister(false)}> Já tenho uma conta </button> </div> )} <ConfirmationModal show={modal.show} message={modal.message} onClose={() => setModal({ show: false, message: "" })} /> </div> ); };

export default LoginRegister;